### ISSUE TITLE
Baleen JSON Parser

### ISSUE THREAD

**Issue by HawaiianSpork** [ShopRunner/baleen#1]
Create Baleen Data objects for validation from JSON file.  Probably using Jackson library.

**Comment by kdallmeyer-sr** [comment]
Wrote something for Jackson in #42 .

Other options could be to use [kotlinx serialization library](https://github.com/Kotlin/kotlinx.serialization) or [moshi](https://github.com/square/moshi). I am not familiar with either enough yet to determine if they support line and column numbers like jackson does.

**Comment by kdallmeyer-sr** [comment]
Jackson support now merged! #42
